name: Deploy Github Repository to OCIR
run-name: ${{ github.actor }} - deploy to OCIR
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install npm dependencies
        run: |
          npm install
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCIR_HOST }}
          username: ${{ secrets.OCIR_USERNAME }}
          key: ${{ secrets.OCIR_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/node-api-proxy-server;
            git pull;
            npm install;
            pm2 restart all;
